name: dlivrDriver
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_icons: ^1.1.0
  device_info: ^2.0.2
  dio: ^4.0.0
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  firebase_crashlytics: ^2.0.4
  firebase_messaging: ^10.0.0
  cached_network_image: ^3.0.0
  cloud_firestore:
  get: ^4.1.4
  image_picker: ^0.7.5+3
  image_cropper: ^1.4.0
  #flutter_login_facebook:
  google_sign_in: ^5.0.4
  package_info: ^2.0.2
  share: ^2.0.4
  shared_preferences: ^2.0.6
  location: ^4.1.1
  url_launcher: ^6.0.4
  intl: ^0.17.0
  percent_indicator: ^2.1.3
  geocoding: ^2.0.0
  google_maps_flutter: ^2.0.6
  google_maps_place_picker: 
  flutter_polyline_points: ^1.0.0
  photo_view: ^0.12.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: 
  build_runner:  

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoR.ttf
    - family: RobotoM
      fonts:
        - asset: assets/fonts/RobotoM.ttf  
    - family: RobotoB
      fonts:
        - asset: assets/fonts/RobotoB.ttf        

